### ISSUE TITLE
[Feature Request] Add OnClick that will generate a new CAPTCHA

### ISSUE THREAD

**Issue by gcarreno** [wp-xyz/captcha_component#1]
Hey WP(@wp-xyz),

In my demo program if you click on the CAPTCHA it generates a new set of chars/lines.

I'm thinking that the CAPTCHAS online have the same functionality, but I'm not completely sure.

So if you could add a `OnClick` event that will call the internal routines to generate and redraw a new CAPTCHA, that would be great :smile: 

Cheers,
Gus

**Comment by wp-xyz** [comment]
Done. See new property NewCaptchaEvent = (nceNone, nceClick, nceDblClick).

**Comment by gcarreno** [comment]
Hey WP(@wp-xyz),

Awesome sauce!!

You even tackled the double click that did bug me on my example app.
If I clicked on it too fast it would trigger the double click event and it would do nothing.
Good catch!!

Cheers,
Gus
