### ISSUE TITLE
[Question] Can your version deal with non Latin chars?

### ISSUE THREAD

**Issue by gcarreno** [wp-xyz/captcha_component#2]
Hey WP(@wp-xyz),

Just stumbled on [this post](https://forum.lazarus.freepascal.org/index.php/topic,56335.msg418868.html#msg418868) from CM630 on the Lazarus forum and he is having problems with Cyrillic when using my version.

Have you tested your version with non Latin chars?

And do you feel that adding the ability to define the allowed chars could be something you're on board with?

Cheers,
Gus

**Comment by wp-xyz** [comment]
No, the catcha that I've seen were always ASCII (unless my memory deceives me). But I changed it to UTF8 now and added string properties for the valid uppercase, lowercase, numeric and special characters. This way the user can taylor the captcha as needed.

**Comment by gcarreno** [comment]
Hey WP(@wp-xyz),

> No, the catpcha that I've seen were always ASCII (unless my memory deceives me).

I don;t think your memory failed you, I have the same impression!!

> But I changed it to UTF8 now and added string properties for the valid uppercase, lowercase, numeric and special characters. This way the user can tailor the captcha as needed.

Many thanks for that!!

I guess that now CM630 can try and use Cyrillic at his heart's content :)

Cheers,
Gus

**Comment by wp-xyz** [comment]
A problem with my way to stuff the valid chars into the component is that the settings must be duplicated for every instance of the component. Alternatively it would have been possible to define the valid chars as variable strings outside the component in a way that the user can change them. But this is a bit less obvious than having them as properties in the object inspector. So, I think I'll take the risk that nobody needs dozens of captcha instances. (But as usual, I might change my mind...)

**Comment by gcarreno** [comment]
Hey WP(@wp-xyz),

Well, it's your component and you do what you wan with it, right? :wink:  LOL!!

Cheers,
Gus
